import asyncio
import re
from unittest.mock import MagicMock, AsyncMock

# Mocking SimEngine for testing
class MockSimEngine:
    def __init__(self):
        pass

    # Copy the updated handle_tools here for testing
    async def handle_tools(self, db, agent, text: str, add_step_cb=None):
        """Parses */ blocks generated by the LLM and executes them via the central router."""
        processed_text = text
        summary = ""
        
        pattern = r"\*/(.*?)/\*"
        matches = list(re.finditer(pattern, text, re.DOTALL))
        
        if not matches:
            return text, None

        for m in reversed(matches):
            inner = m.group(1)
            parts = [p.strip() for p in inner.split("|") if p.strip()]
            if not parts: continue
            
            tool_name = parts[0]
            args = parts[1:]

            # Hand off to the exact same execution logic that parses inline prompt commands!
            if add_step_cb:
                add_step_cb("tool_call", f"Calling {tool_name}", {"tool": tool_name, "args": args})
            
            result = await self._execute_inline_command(tool_name, args, db, agent, add_step_cb)
            
            if add_step_cb:
                add_step_cb("tool_result", f"Result for {tool_name}", {"tool": tool_name, "result": result})
            
            # Formatting the result back into the text
            result_str = f"\n\n> **TOOL RESULT**: `{tool_name}` -> {result}\n\n"
            processed_text = processed_text[:m.start()] + result_str + processed_text[m.end():]
            summary = f"{tool_name}: {result[:50]}\n" + summary
            
            # Stop processing further tools if we hit a bankruptcy flag from the executor
            if "INSUFFICIENT_FUNDS" in result or "TOOL_NO_FUNDS" in result:
                break
            
        return processed_text, summary

    async def _execute_inline_command(self, tool_name, args, db, agent, add_step_cb):
        return f"MOCK_RESULT_FOR_{tool_name}_WITH_{'_'.join(args)}"

async def main():
    engine = MockSimEngine()
    db = MagicMock()
    agent = MagicMock()
    
    test_cases = [
        "I will check the data. */web_search|Living in Dakhla/* and then I will wait.",
        "Multiple calls: */get_time/* and */create_thread|Topic|Aim/*",
        "No args: */get_time/*",
        "Pipe in args: */tool|arg1|arg2 with | pipe/*", # This might be tricky
        "Empty: something */ /* nothing"
    ]
    
    for i, text in enumerate(test_cases):
        print(f"\n--- Test Case {i+1} ---")
        print(f"Input: {text}")
        processed, summary = await engine.handle_tools(db, agent, text)
        print(f"Processed: {processed}")
        print(f"Summary: {summary}")

if __name__ == "__main__":
    asyncio.run(main())
